apiVersion: v1
kind: Service
metadata:
  name: loan-service
  namespace: homestarter-ns
spec:
  type: ClusterIP
  selector:
    app: loan-service
  ports:
    - port: 80
      targetPort: 8083
      protocol: TCP
