apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-common
  namespace: homestarter-ns
data:
  CORS_ALLOWED_ORIGINS: "http://localhost:8081,http://localhost:8082,http://localhost:8083,http://localhost:8084,http://homestarter.172.30.1.205.nip.io"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  JWT_ACCESS_TOKEN_VALIDITY: "1800"
  JWT_REFRESH_TOKEN_VALIDITY: "86400"
  LOG_LEVEL_APP: "DEBUG"
  LOG_LEVEL_WEB: "INFO"
  LOG_LEVEL_SQL: "DEBUG"
  LOG_LEVEL_SQL_TYPE: "TRACE"
