apiVersion: v1
kind: Secret
metadata:
  name: secret-common
  namespace: homestarter-ns
type: Opaque
stringData:
  JWT_SECRET: "siTTeU7IVrPkbSSCf9AcLoTu5LVF8kJhSmHp5rm7t/I="
  REDIS_PASSWORD: "Vnawmd135*"
