apiVersion: v1
kind: Secret
metadata:
  name: homestarter
  namespace: homestarter-ns
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"docker.io":{"username":"daewoongjeon","password":"Vnawmd135*","auth":"ZGFld29vbmdqZW9uOlZuYXdtZDEzNSo="}}}'
