apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-calculator-service
  namespace: homestarter-ns
data:
  SERVER_PORT: "8085"
  DB_KIND: "postgresql"
  DB_PORT: "5432"
  DB_NAME: "homestarterdb"
  DDL_AUTO: "update"
  SHOW_SQL: "true"
  REDIS_DATABASE: "2"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  USER_SERVICE_URL: "http://user-service"
  ASSET_SERVICE_URL: "http://asset-service"
  HOUSING_SERVICE_URL: "http://housing-service"
  LOAN_SERVICE_URL: "http://loan-service"
  LOG_FILE_PATH: "logs/calculator-service.log"
