apiVersion: v1
kind: Service
metadata:
  name: calculator-service
  namespace: homestarter-ns
spec:
  type: ClusterIP
  selector:
    app: calculator-service
  ports:
    - port: 80
      targetPort: 8085
      protocol: TCP
