apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-asset-service
  namespace: homestarter-ns
data:
  SERVER_PORT: "8082"
  DB_KIND: "postgresql"
  DB_PORT: "5432"
  DB_NAME: "homestarterdb"
  DDL_AUTO: "update"
  SHOW_SQL: "true"
  REDIS_DATABASE: "2"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  LOG_FILE_PATH: "logs/asset-service.log"
  CORS_ALLOWED_ORIGINS: "http://localhost:*,http://121.129.45.98:8080"
