apiVersion: v1
kind: Secret
metadata:
  name: secret-asset-service
  namespace: homestarter-ns
type: Opaque
stringData:
  DB_HOST: "postgres-postgresql"
  DB_USERNAME: "homestarteruser"
  DB_PASSWORD: "Vnawmd135*"
