apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-housing-service
  namespace: homestarter-ns
data:
  SERVER_PORT: "8084"
  DB_KIND: "postgresql"
  DB_PORT: "5432"
  DB_NAME: "homestarterdb"
  DDL_AUTO: "update"
  SHOW_SQL: "true"
  REDIS_DATABASE: "2"
  LOG_FILE_PATH: "logs/housing-service.log"
