apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-roadmap-service
  namespace: homestarter-ns
data:
  SERVER_PORT: "8086"
  DB_KIND: "postgresql"
  DB_PORT: "5432"
  DB_NAME: "homestarterdb"
  DDL_AUTO: "update"
  SHOW_SQL: "true"
  REDIS_DATABASE: "2"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  USER_SERVICE_URL: "http://user-service"
  ASSET_SERVICE_URL: "http://asset-service"
  HOUSING_SERVICE_URL: "http://housing-service"
  CALCULATOR_SERVICE_URL: "http://calculator-service"
  LLM_API_URL: "https://api.openai.com"
  LOG_FILE_PATH: "logs/roadmap-service.log"
  CORS_ALLOWED_ORIGINS: "http://localhost:*,http://121.129.45.98:8080"
