apiVersion: apps/v1
kind: Deployment
metadata:
  name: roadmap-service
  namespace: homestarter-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roadmap-service
  template:
    metadata:
      labels:
        app: roadmap-service
    spec:
      imagePullSecrets:
        - name: homestarter
      containers:
        - name: roadmap-service
          image: docker.io/daewoongjeon/roadmap-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: cm-common
            - configMapRef:
                name: cm-roadmap-service
            - secretRef:
                name: secret-common
            - secretRef:
                name: secret-roadmap-service
          resources:
            requests:
              cpu: 256m
              memory: 128Mi
            limits:
              cpu: 256m
              memory: 128Mi
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            initialDelaySeconds: 5
            periodSeconds: 15
            failureThreshold: 3
