apiVersion: v1
kind: Service
metadata:
  name: roadmap-service
  namespace: homestarter-ns
spec:
  type: ClusterIP
  selector:
    app: roadmap-service
  ports:
    - port: 80
      targetPort: 8086
      protocol: TCP
